export interface FrameworkDef {
  /** Identifier used in `/vforge <id> <prompt>`. */
  id: string;
  label: string;
  aliases: string[];
  /** Folder name under templates/. */
  template: string;
  /** Rules injected into the lock file and read by every vforge skill. */
  rules: string[];
  /** One-line instruction for adding a page (used by /page). */
  pageRule: string;
  /** Where reusable components live (used by /component). */
  componentsDir: string;
  /** Stack bullet list for PROJECT.md. */
  stack: string[];
  buildCmd: string;
}

export const FRAMEWORKS: FrameworkDef[] = [
  {
    id: "next",
    label: "Next.js (App Router)",
    aliases: [],
    template: "next-shadcn-base",
    rules: [
      "Use Next.js App Router and TypeScript. Routes live under `app/`; `page.tsx` defines a route.",
      "Components live in `components/` and `components/ui/`; helpers in `lib/`. Import alias: `@/*` -> project root.",
      "Add `\"use client\"` only to components that use state, effects or browser APIs.",
      "Backend: use Route Handlers under `app/api/` only if the prompt asks for it.",
    ],
    pageRule: "Create `app/<kebab-name>/page.tsx` using Next.js App Router conventions.",
    componentsDir: "components/",
    stack: ["Next.js App Router", "TypeScript", "Tailwind CSS", "shadcn-style source components", "lucide-react", "Bun"],
    buildCmd: "bun run build",
  },
  {
    id: "vite",
    label: "Vite + React (SPA)",
    aliases: [],
    template: "vite-react-shadcn-base",
    rules: [
      "Use Vite + React + TypeScript as a client-side SPA. Entry: `src/main.tsx` -> `src/App.tsx`.",
      "Page-level components live in `src/routes/`; reusable ones in `src/components/` and `src/components/ui/`; helpers in `src/lib/`. Import alias: `@/*` -> `src/*`.",
      "For multiple pages add `react-router-dom` (`bun add react-router-dom`) and a router in `src/App.tsx`. Do not add it for single-page apps.",
      "There is no server: no API routes, no server components. Use mocked data unless the prompt demands a backend.",
    ],
    pageRule:
      "Create `src/routes/<kebab-name>.tsx` exporting a default component. If the app has no router yet, install `react-router-dom` and wire the routes in `src/App.tsx`.",
    componentsDir: "src/components/",
    stack: ["Vite", "React", "TypeScript", "Tailwind CSS v4", "shadcn-style source components", "lucide-react", "Bun"],
    buildCmd: "bun run build",
  },
  {
    id: "react-router",
    label: "React Router v7 (framework mode)",
    aliases: ["rr"],
    template: "react-router-shadcn-base",
    rules: [
      "Use React Router v7 framework mode (SSR) with TypeScript. App directory is `src/` (see `react-router.config.ts`).",
      "Routes are declared in `src/routes.ts` (config-based, not file-based). Route modules live in `src/routes/`.",
      "Route modules may export `loader`, `action`, `meta` and a default component. Types come from `./+types/<module>` (generated by `react-router typegen`, which `bun run build` runs).",
      "Reusable components live in `src/components/` and `src/components/ui/`; helpers in `src/lib/`. Import alias: `@/*` -> `src/*`.",
      "Prefer loaders returning mocked data over client fetching. Add backend logic only if the prompt asks for it.",
    ],
    pageRule:
      "Create `src/routes/<kebab-name>.tsx` with a default component and register it in `src/routes.ts` with `route(\"<path>\", \"routes/<kebab-name>.tsx\")`.",
    componentsDir: "src/components/",
    stack: ["React Router v7 (framework mode)", "TypeScript", "Tailwind CSS v4", "shadcn-style source components", "lucide-react", "Bun"],
    buildCmd: "bun run build",
  },
  {
    id: "tanstack",
    label: "TanStack Start",
    aliases: ["tanstack-start"],
    template: "tanstack-start-shadcn-base",
    rules: [
      "Use TanStack Start (TanStack Router, file-based routing) with TypeScript. Routes live in `src/routes/`.",
      "`src/routes/__root.tsx` is the document shell; `src/routes/index.tsx` is `/`. Each route file exports `Route = createFileRoute(\"<path>\")({ component })`.",
      "`src/routeTree.gen.ts` is generated by the build. Never edit it by hand.",
      "Reusable components live in `src/components/` and `src/components/ui/`; helpers in `src/lib/`. Import alias: `@/*` -> `src/*`.",
      "Use `Link` from `@tanstack/react-router` for navigation. Server logic only via `createServerFn` and only if the prompt asks for it.",
    ],
    pageRule:
      "Create `src/routes/<kebab-name>.tsx` exporting `Route = createFileRoute(\"/<kebab-name>\")({ component })`. The route tree regenerates on build.",
    componentsDir: "src/components/",
    stack: ["TanStack Start", "TanStack Router", "TypeScript", "Tailwind CSS v4", "shadcn-style source components", "lucide-react", "Bun"],
    buildCmd: "bun run build",
  },
];

export const DEFAULT_FRAMEWORK = "next";

export function getFramework(id: string): FrameworkDef | undefined {
  const needle = id.toLowerCase();
  return FRAMEWORKS.find((f) => f.id === needle || f.aliases.includes(needle));
}

export interface ParsedArgs {
  framework: FrameworkDef;
  prompt: string;
  /** True when the first token was not a framework and the default was used. */
  usedDefault: boolean;
}

/** Parses `/vforge [framework] <prompt>`. Falls back to Next.js for backward compatibility. */
export function parseArgs(args: string): ParsedArgs {
  const trimmed = args.trim();
  const [first = "", ...rest] = trimmed.split(/\s+/);
  const match = first ? getFramework(first) : undefined;
  if (match) return { framework: match, prompt: rest.join(" ").trim(), usedDefault: false };
  return { framework: getFramework(DEFAULT_FRAMEWORK)!, prompt: trimmed, usedDefault: true };
}

export function usageText(): string {
  const lines = FRAMEWORKS.map((f) => `- \`/vforge ${f.id} <description>\` — ${f.label}`);
  return ["Usage: /vforge <framework> <app description>", "", ...lines, "", "If the framework is omitted, `next` is used."].join("\n");
}
