export interface ProjectMetadata {
  slug: string;
  prompt: string;
  spec: string;
  visualDirection: string;
  outputPath: string;
  buildPassed: boolean;
  repairAttempts: number;
  previewUrl?: string;
  /** Framework id, e.g. "vite". Defaults to "next" in rendered output. */
  framework?: string;
  stack?: string[];
}

export function renderProjectMd(meta: ProjectMetadata): string {
  const lines = [
    "# Project Brief",
    "",
    `**Generated by:** vforge`,
    `**Slug:** ${meta.slug}`,
    `**Framework:** ${meta.framework ?? "next"}`,
    `**Created:** ${new Date().toISOString()}`,
    "",
    "## Original Prompt",
    "",
    meta.prompt,
    "",
    "## Implementation Spec",
    "",
    meta.spec,
    "",
    "## Visual Direction",
    "",
    meta.visualDirection,
    "",
    "## Project Location",
    "",
    meta.outputPath,
    "",
    "## Build Status",
    "",
    `- Passed: ${meta.buildPassed ? "yes" : "no"}`,
    `- Repair attempts: ${meta.repairAttempts}/3`,
    meta.previewUrl ? `- Preview: ${meta.previewUrl}` : "",
    "",
    "## Working with this project",
    "",
    "Open this directory with opencode. The following commands are available:",
    "",
    "- `/iterate <prompt>` — evolve or refactor the app.",
    "- `/page <name>` — add a new page.",
    "- `/component <name>` — add a new component.",
    "- `/vforge <framework> <prompt>` — generate another project (next, vite, react-router, tanstack).",
    "",
    "## Stack",
    "",
    ...(meta.stack ?? ["Next.js App Router", "TypeScript", "Tailwind CSS", "shadcn-style source components", "lucide-react", "Bun"]).map((item) => `- ${item}`),
    "",
    "## Notes",
    "",
    "Keep this file as the source of truth for the project's intent. When iterating, reference it so later changes stay aligned with the original goals.",
  ];

  return lines.join("\n");
}
