export interface ProjectMetadata {
  slug: string;
  prompt: string;
  spec: string;
  visualDirection: string;
  outputPath: string;
  buildPassed: boolean;
  repairAttempts: number;
  previewUrl?: string;
}

export function renderProjectMd(meta: ProjectMetadata): string {
  const lines = [
    "# Project Brief",
    "",
    `**Generated by:** vforge`,
    `**Slug:** ${meta.slug}`,
    `**Created:** ${new Date().toISOString()}`,
    "",
    "## Original Prompt",
    "",
    meta.prompt,
    "",
    "## Implementation Spec",
    "",
    meta.spec,
    "",
    "## Visual Direction",
    "",
    meta.visualDirection,
    "",
    "## Project Location",
    "",
    meta.outputPath,
    "",
    "## Build Status",
    "",
    `- Passed: ${meta.buildPassed ? "yes" : "no"}`,
    `- Repair attempts: ${meta.repairAttempts}/3`,
    meta.previewUrl ? `- Preview: ${meta.previewUrl}` : "",
    "",
    "## Working with this project",
    "",
    "Open this directory with opencode. The following commands are available:",
    "",
    "- `/iterate <prompt>` — evolve or refactor the app.",
    "- `/page <name>` — add a new page.",
    "- `/component <name>` — add a new component.",
    "- `/vforge next` — generate another project.",
    "",
    "## Stack",
    "",
    "- Next.js App Router",
    "- TypeScript",
    "- Tailwind CSS",
    "- shadcn-style source components",
    "- lucide-react",
    "- Bun",
    "",
    "## Notes",
    "",
    "Keep this file as the source of truth for the project's intent. When iterating, reference it so later changes stay aligned with the original goals.",
  ];

  return lines.join("\n");
}
